# Generated by Django 5.2.3 on 2025-10-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinario',
            name='especialidad',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('hamster', 'Hámster')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
