# Generated by Django 5.2.3 on 2025-09-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')]),
        ),
    ]
