# Generated by Django 5.2.3 on 2025-09-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_animal_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='disponibleAdopcion',
            field=models.BooleanField(default=False, verbose_name='¿Está disponible para adopción?'),
        ),
    ]
