# Generated by Django 5.2.3 on 2025-10-01 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_animal_disponibleadopcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencionmedica',
            name='tratamiento',
        ),
        migrations.RemoveField(
            model_name='atencionmedica',
            name='diagnostico',
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('hamster', 'Hámster')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='atencionmedica',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='atencionmedica',
            name='vacuna_aplicada',
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('hamster', 'Hámster')]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('atencionmedica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Usuarios.atencionmedica')),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
            ],
            bases=('Usuarios.atencionmedica',),
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('atencionmedica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Usuarios.atencionmedica')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.vacuna')),
            ],
            bases=('Usuarios.atencionmedica',),
        ),
    ]
