# Generated by Django 5.2.3 on 2025-10-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_consulta_diagnostico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
