# Generated by Django 5.0 on 2025-07-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediosTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(auto_created='NAV-xxxx', max_length=15, unique=True)),
                ('tipo', models.CharField(choices=[('omnibes', 'omnibus'), ('camion', 'camion'), ('automovil', 'automovil')], max_length=20)),
                ('estado', models.CharField(choices=[('operativo', 'operativo'), ('mantenimiento', 'mantenimiento')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('origen', models.CharField(max_length=20)),
                ('destino', models.CharField(max_length=20)),
                ('cantkm', models.PositiveIntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Terminales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=30, unique=True)),
                ('ubicacion', models.CharField(choices=[('urbana', 'urbana'), ('rural', 'rural')], max_length=20)),
            ],
        ),
    ]
