# Generated by Django 4.2.7 on 2025-09-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediostransporte',
            name='estado',
            field=models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'Mantenimiento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mediostransporte',
            name='matricula',
            field=models.CharField(default='NAV-xxxx', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='mediostransporte',
            name='tipo',
            field=models.CharField(choices=[('omnibus', 'Ómnibus'), ('camion', 'Camión'), ('automovil', 'Automóvil')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rutas',
            name='cantkm',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='terminales',
            name='ubicacion',
            field=models.CharField(choices=[('urbana', 'Urbana'), ('rural', 'Rural')], max_length=20),
        ),
    ]
