# Generated by Django 4.2.7 on 2025-09-20 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_alter_mediostransporte_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('software', 'Desarrollo de Software'), ('marketing', 'Marketing Digital'), ('diseno', 'Diseño Gráfico'), ('redaccion', 'Redacción de Contenidos')], max_length=20)),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('fecha_limite', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='myapp.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisada', 'Revisada'), ('contactado', 'Contactado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='myapp.candidato')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='myapp.ofertatrabajo')),
            ],
            options={
                'unique_together': {('candidato', 'oferta')},
            },
        ),
        migrations.DeleteModel(
            name='MediosTransporte',
        ),
        migrations.DeleteModel(
            name='Rutas',
        ),
        migrations.DeleteModel(
            name='Terminales',
        ),
    ]
