# Generated by Django 5.2.3 on 2025-10-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_alter_vacuna_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
