# Generated by Django 5.2 on 2025-10-02 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='requester',
            field=models.ForeignKey(limit_choices_to={'role__in': ['client', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='rental_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tools.rentalrequest'),
        ),
        migrations.AddField(
            model_name='tool',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role__in': ['provider', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='tools.tool'),
        ),
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.toolcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('rater', 'rental_request')},
        ),
        migrations.AddConstraint(
            model_name='rentalrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('tool',), name='unique_pending_request_per_tool'),
        ),
    ]
