# Generated by Django 5.2 on 2025-11-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='condition',
            field=models.CharField(choices=[('new', 'Nueva'), ('excellent', 'Excelente'), ('good', 'Buena'), ('fair', 'Regular'), ('poor', 'Desgastada')], default='good', help_text='Estado físico de la herramienta', max_length=20),
        ),
    ]
