# Generated by Django 5.2.7 on 2025-12-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Almacenero', 'Almacenero'), ('Vendedor', 'Vendedor')], default='Vendedor', max_length=10),
        ),
    ]
