# Generated by Django 5.2.1 on 2025-11-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente')], default='cliente', max_length=10),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='especialidad',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('hamster', 'Hámster')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tratamiento',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
