# Generated by Django 5.2.3 on 2025-10-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_alter_vacuna_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'admin'), ('cliente', 'cliente')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
