# Generated by Django 5.2.2 on 2025-10-30 04:52

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attachment',
            field=models.FileField(blank=True, help_text='CV o portafolio en PDF (máx 5MB)', null=True, upload_to=core.models.Application.application_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
