# Generated by Django 4.2.7 on 2025-11-11 05:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='deadline',
            field=models.DateField(default=core.models.JobOffer.default_deadline),
        ),
    ]
