# Generated by Django 5.2 on 2025-11-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categorias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="nombre",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
