# Generated by Django 5.2.7 on 2025-11-01 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categorias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=6)),
                ("precio_venta", models.DecimalField(decimal_places=2, max_digits=6)),
                ("cantidad", models.IntegerField()),
                ("descripcion", models.TextField()),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="categorias.categoria",
                    ),
                ),
            ],
        ),
    ]
