# Generated by Django 5.2.7 on 2025-11-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_producto_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
