# Generated by Django 5.2 on 2025-11-25 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categorias", "0002_alter_categoria_nombre"),
        ("productos", "0003_alter_producto_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="nombre_categoria",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos",
                to="categorias.categoria",
            ),
        ),
    ]
