# Generated by Django 5.2 on 2025-11-25 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0004_producto_nombre_categoria_alter_producto_categoria"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="nombre_categoria",
            new_name="categoria_nombre",
        ),
    ]
