# Generated by Django 5.2 on 2025-10-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('provider', 'Proveedor'), ('client', 'Cliente'), ('both', 'Ambos'), ('admin', 'Administrador')], default='client', help_text='Rol del usuario en la plataforma', max_length=10),
        ),
    ]
