# Generated by Django 5.2 on 2025-11-10 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_role', models.CharField(choices=[('provider', 'Proveedor'), ('client', 'Cliente'), ('both', 'Ambos'), ('admin', 'Administrador')], help_text='Rol actual del usuario', max_length=10)),
                ('requested_role', models.CharField(choices=[('provider', 'Proveedor'), ('client', 'Cliente'), ('both', 'Ambos'), ('admin', 'Administrador')], help_text='Rol solicitado por el usuario', max_length=10)),
                ('reason', models.TextField(help_text='Razón o justificación del cambio de rol')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', help_text='Estado de la solicitud', max_length=10)),
                ('admin_response', models.TextField(blank=True, help_text='Respuesta del administrador', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la solicitud')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Fecha de revisión por el administrador', null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Administrador que revisó la solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_role_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Usuario que solicita el cambio de rol', on_delete=django.db.models.deletion.CASCADE, related_name='role_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio de Rol',
                'verbose_name_plural': 'Solicitudes de Cambio de Rol',
                'ordering': ['-created_at'],
            },
        ),
    ]
